<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_htmloverflow-yscrollimportant</name>
   <tag></tag>
   <elementGuidId>953d3da1-38dd-400a-909e-bed1ea2872d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='splash-screen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#splash-screen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b97ef42f-7664-4dd1-850c-0b33cbdf9a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>splash-screen</value>
      <webElementGuid>4cc0cb5a-da94-4fff-b395-9f74e1a6ebef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>html{overflow-y:scroll!important}</value>
      <webElementGuid>b4ae7698-1d21-48e9-a912-828d93aece1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;splash-screen&quot;)</value>
      <webElementGuid>b15861b1-f3bb-49e3-9989-c80b86b94333</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='splash-screen']</value>
      <webElementGuid>faf4877c-9966-4c5e-ac9e-1c7c255c59f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>9884eb42-4102-477d-bdb6-ba8ad3c571d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'splash-screen' and (text() = 'html{overflow-y:scroll!important}' or . = 'html{overflow-y:scroll!important}')]</value>
      <webElementGuid>4674d9b1-e39a-481a-a7a9-dab962c2f6ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
