<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Get strong today</name>
   <tag></tag>
   <elementGuidId>9bd0e196-4d81-4ac5-8af2-77157ce8c0f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide-12-layer-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slide-12-layer-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>82e19277-ab06-4263-9dc2-e154dbeea68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-caption   tp-resizeme</value>
      <webElementGuid>8a512085-49a1-4164-9744-4f7b118594a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>slide-12-layer-10</value>
      <webElementGuid>4706d83b-4f8a-4c59-a731-bb43f060b878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x</name>
      <type>Main</type>
      <value>['left','left','left','left']</value>
      <webElementGuid>80f478d9-721c-4a91-bea0-02682eeb16d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hoffset</name>
      <type>Main</type>
      <value>['0','0','0','15']</value>
      <webElementGuid>64b12a35-049b-443a-87ed-f5ab1a31687e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y</name>
      <type>Main</type>
      <value>['middle','middle','middle','middle']</value>
      <webElementGuid>925ff986-25b5-459f-917c-f8f124253e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-voffset</name>
      <type>Main</type>
      <value>['0','-16','-116','-36']</value>
      <webElementGuid>ffa35cb9-1625-4ff3-92f9-ad828303d319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-fontsize</name>
      <type>Main</type>
      <value>['95','95','95','50']</value>
      <webElementGuid>03aceb75-ee18-478b-b6c9-7c44d9ad3e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lineheight</name>
      <type>Main</type>
      <value>['90','90','90','50']</value>
      <webElementGuid>d3c35cc6-f54f-4817-9f2b-ab746d9686c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-letterspacing</name>
      <type>Main</type>
      <value>['19','19','19','10']</value>
      <webElementGuid>dd51f9ca-4754-4b57-86a4-2e397592be97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-width</name>
      <type>Main</type>
      <value>['595','585','586','219']</value>
      <webElementGuid>f838e8a8-46ca-4182-9493-e67e3317f41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-height</name>
      <type>Main</type>
      <value>['181','181','181','151']</value>
      <webElementGuid>1e0dcb60-2287-4ec0-8ea9-9932fa486d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-whitespace</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>d31713ef-4fba-4cd1-90d6-776ba6a58ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>feea24b8-3322-475e-b6bc-d113f9262a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-responsive_offset</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>b512f677-a346-4f20-8271-6a7e999d7a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-frames</name>
      <type>Main</type>
      <value>[{&quot;delay&quot;:600,&quot;speed&quot;:700,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;x:50px;opacity:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power2.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:300,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;opacity:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;}]</value>
      <webElementGuid>096026bf-4936-4124-85eb-0f0922bbf7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-textalign</name>
      <type>Main</type>
      <value>['inherit','inherit','inherit','inherit']</value>
      <webElementGuid>be9f33c8-f166-4739-ab09-aed8c8079f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingtop</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>7f65127c-15ef-4625-8904-c84f954d12d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingright</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>3cb06a51-663c-4f90-b0c1-28f7c0dc63b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingbottom</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>f0ee23ca-8558-4ddd-95b0-dbb23fb0753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-paddingleft</name>
      <type>Main</type>
      <value>[0,0,0,0]</value>
      <webElementGuid>53b180d3-1a59-4189-8633-24708f6cd841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get strong today
 </value>
      <webElementGuid>c372457e-bdd2-4903-9128-87b79ffe9b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-12-layer-10&quot;)</value>
      <webElementGuid>fdfd0245-065b-4144-b9b2-b204bf7bac49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='slide-12-layer-10']</value>
      <webElementGuid>e29a713e-d313-44e3-88b7-310b46a8c38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rev_slider_6_1']/ul/li/div[5]/div/div/div</value>
      <webElementGuid>aaefa384-41d5-49f6-80b1-49d9acfcfc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[3]/following::div[32]</value>
      <webElementGuid>505f0ad7-911a-4e27-b4e5-36db9c7413c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[3]/following::div[32]</value>
      <webElementGuid>89d7ad71-5485-42ef-be5b-d0052bcf3f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/'])[1]/preceding::div[10]</value>
      <webElementGuid>f7d9d2c7-e477-4375-873c-3a4bbad2a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sandy'])[1]/preceding::div[13]</value>
      <webElementGuid>cac44717-fd65-44a7-9391-227da4bcd5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get strong today']/parent::*</value>
      <webElementGuid>854431fc-52ca-46dd-a5d6-f174ae6e0704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div</value>
      <webElementGuid>9944a8aa-5a69-4ac4-bb87-48848ac33bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'slide-12-layer-10' and (text() = 'Get strong today
 ' or . = 'Get strong today
 ')]</value>
      <webElementGuid>a30f1870-0909-4622-8106-11485b30df2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
