<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TentangLihat SemuaDaerah Khusus Ibukota_dac4caFB</name>
   <tag></tag>
   <elementGuidId>0a8766f0-0ea6-45b1-80d0-ad33cfac8a7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_DA']/div/div/div/div[3]/div/div/div/div/div/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.x9f619.x1n2onr6.x1ja2u2z.x2lah0s.x1qjc9v5.x78zum5.x1q0g3np.x1a02dak.xl56j7k.x9otpla.x1n0m28w.x1wsgfga.xp7jhwk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fadea125-d684-4f8b-95d1-9517b8e03ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x9f619 x1n2onr6 x1ja2u2z x2lah0s x1qjc9v5 x78zum5 x1q0g3np x1a02dak xl56j7k x9otpla x1n0m28w x1wsgfga xp7jhwk</value>
      <webElementGuid>c590862b-5157-4766-b127-910008283e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tentang Lihat SemuaDaerah Khusus Ibukota Jakarta 1294012 orang menyukai ini12 orang mengikuti ini734 orang singgah di sinihttp://www.fitbybeat.com/(021) 5211982Kisaran harga  · $$Buka06.00 - 22.00Gym/Pusat Kebugaran FisikTransparansi Halaman Lihat SemuaFacebook menampilkan informasi untuk membantu Anda memahami tujuan Halaman dengan lebih baik. Lihat tindakan yang diambil oleh orang yang mengelola dan memposting konten.Halaman dibuat - 7 April 2016Privasi  · Ketentuan  · Iklan  · Pilihan Iklan   · Cookie  · Lainnya  · Meta © 2023Postingan Tentang Fit By BeatSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikPUSH YOUR LIMITS !Semua tanggapan:15SukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentarifitbybeat.arkadia sedang di Fit By Beat.  · 15 Juni 2022  · Jakarta  · Dibagikan kepada PublikYou gotta hustle for that muscle, join our trainer @dwijo.saputro  for your intense training session#fitness #fitbybeat #fbb #class #strong #powerful #newoutlet #newfitnewbeat #fitisthenewskinny #beastmode #2022 #newyears #newresolution #newhope #gym #gymclass #timetable #personaltrainer #personaltrainerjakarta0:00 / 0:13SukaKomentari</value>
      <webElementGuid>7afad56b-f343-4f2f-9f5f-411444774f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_DA&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1t2pt76 x1n2onr6 x1ja2u2z x10cihs4&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1t2pt76 x1n2onr6&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1iyjqo2&quot;]/div[@class=&quot;x9f619 x193iq5w x1talbiv x1swvt13 x1pi30zi xkrivgy x1gryazu xyamay9&quot;]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z x2lah0s x1qjc9v5 x78zum5 x1q0g3np x1a02dak xl56j7k x9otpla x1n0m28w x1wsgfga xp7jhwk&quot;]</value>
      <webElementGuid>9d78926a-82bb-41ee-a0bd-34e9de5f3d5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_DA']/div/div/div/div[3]/div/div/div/div/div/div[4]/div/div</value>
      <webElementGuid>f72d0a59-de01-4587-b32c-a81dadcd95e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fit By Beat'])[2]/following::div[13]</value>
      <webElementGuid>d2977ec4-5af6-4670-b2c8-8a9fa0fac03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ulasan'])[2]/following::div[28]</value>
      <webElementGuid>2c36dae2-49fc-43d3-aae9-bf8e3341e98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>baa530fb-838e-47e7-9beb-a955ace483d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Tentang Lihat SemuaDaerah Khusus Ibukota Jakarta 1294012 orang menyukai ini12 orang mengikuti ini734 orang singgah di sinihttp://www.fitbybeat.com/(021) 5211982Kisaran harga  · $$Buka06.00 - 22.00Gym/Pusat Kebugaran FisikTransparansi Halaman Lihat SemuaFacebook menampilkan informasi untuk membantu Anda memahami tujuan Halaman dengan lebih baik. Lihat tindakan yang diambil oleh orang yang mengelola dan memposting konten.Halaman dibuat - 7 April 2016Privasi  · Ketentuan  · Iklan  · Pilihan Iklan   · Cookie  · Lainnya  · Meta © 2023Postingan Tentang Fit By BeatSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikPUSH YOUR LIMITS !Semua tanggapan:15SukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentarifitbybeat.arkadia sedang di Fit By Beat.  · 15 Juni 2022  · Jakarta  · Dibagikan kepada PublikYou gotta hustle for that muscle, join our trainer @dwijo.saputro  for your intense training session#fitness #fitbybeat #fbb #class #strong #powerful #newoutlet #newfitnewbeat #fitisthenewskinny #beastmode #2022 #newyears #newresolution #newhope #gym #gymclass #timetable #personaltrainer #personaltrainerjakarta0:00 / 0:13SukaKomentari' or . = 'Tentang Lihat SemuaDaerah Khusus Ibukota Jakarta 1294012 orang menyukai ini12 orang mengikuti ini734 orang singgah di sinihttp://www.fitbybeat.com/(021) 5211982Kisaran harga  · $$Buka06.00 - 22.00Gym/Pusat Kebugaran FisikTransparansi Halaman Lihat SemuaFacebook menampilkan informasi untuk membantu Anda memahami tujuan Halaman dengan lebih baik. Lihat tindakan yang diambil oleh orang yang mengelola dan memposting konten.Halaman dibuat - 7 April 2016Privasi  · Ketentuan  · Iklan  · Pilihan Iklan   · Cookie  · Lainnya  · Meta © 2023Postingan Tentang Fit By BeatSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikPUSH YOUR LIMITS !Semua tanggapan:15SukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentariSubhan Prasandra sedang di Fit By Beat.  · 14 Agustus pada 14.35  · Jakarta  · Dibagikan kepada PublikSukaKomentarifitbybeat.arkadia sedang di Fit By Beat.  · 15 Juni 2022  · Jakarta  · Dibagikan kepada PublikYou gotta hustle for that muscle, join our trainer @dwijo.saputro  for your intense training session#fitness #fitbybeat #fbb #class #strong #powerful #newoutlet #newfitnewbeat #fitisthenewskinny #beastmode #2022 #newyears #newresolution #newhope #gym #gymclass #timetable #personaltrainer #personaltrainerjakarta0:00 / 0:13SukaKomentari')]</value>
      <webElementGuid>017cc343-4fa0-46ec-8b0f-422660e211f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
