<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d1953084-9c4a-4a98-9f75-34f25edba736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slide-12-layer-8']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#slide-12-layer-8 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e5fc1621-33da-460a-a7e5-c019a4624e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://beta.fitbybeat.com/wp-content/uploads/revslider/main-home/h1-slider2-img-1.png</value>
      <webElementGuid>2e94fd61-0e6b-464c-a4b2-f25645fa75d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ww</name>
      <type>Main</type>
      <value>['901','499px','401','401px']</value>
      <webElementGuid>ccaeb66c-5b2a-43a3-a44d-c456eef3e04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hh</name>
      <type>Main</type>
      <value>['1351px','748px','601px','490px']</value>
      <webElementGuid>89c66db2-11c5-4c5c-936c-7975b56c4269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slide-12-layer-8&quot;)/img[1]</value>
      <webElementGuid>a40756b5-92e8-43e8-8fe2-9eebb98a8ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slide-12-layer-8']/img</value>
      <webElementGuid>77cc77ab-5e8b-41fd-bd1e-4ef79605fa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://beta.fitbybeat.com/wp-content/uploads/revslider/main-home/h1-slider2-img-1.png')]</value>
      <webElementGuid>b02cf7ae-1f12-4cf6-ac62-5e38159cdbc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/img</value>
      <webElementGuid>fdd99016-d5ad-427f-8f03-940f81bfcb3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://beta.fitbybeat.com/wp-content/uploads/revslider/main-home/h1-slider2-img-1.png']</value>
      <webElementGuid>158fc604-9a80-4d5b-95d3-ed4fa13b378c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
