<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sex</name>
   <tag></tag>
   <elementGuidId>093311db-d321-4d25-ab6b-85b2e8b4ba0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-sex-14-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-sex-14-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52ae9205-1632-43d0-8c48-bfd9996d0b92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>5f3a64cc-9f04-48da-9bb0-0a7c0b37cf0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-sex-14-container</value>
      <webElementGuid>f46abfeb-3445-41ae-8211-34e56506f1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>3de7281d-24f2-4e89-9127-ab70cec2acb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sex</value>
      <webElementGuid>ad44e2b4-9d41-4389-b553-907f0f2a7880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-sex-14-container&quot;)</value>
      <webElementGuid>976b1895-63ec-43be-b54b-920b960df338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-sex-14-container']</value>
      <webElementGuid>c3ddf369-15b7-4a00-8d2a-fb628f43e669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate Your BMI'])[1]/following::span[4]</value>
      <webElementGuid>37d72e46-3ed8-4930-a072-263f5e8e994b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BMI'])[2]/following::span[4]</value>
      <webElementGuid>ca17a212-8166-489c-8fb9-bbe4324f10c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an activity factor:'])[2]/preceding::span[3]</value>
      <webElementGuid>f5de07f0-b273-4bb7-ab28-b462ec5cc7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate'])[1]/preceding::span[9]</value>
      <webElementGuid>9e7fd827-eca8-4e5c-ad95-a9848caf7b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>5eb0fe19-d37b-4602-9037-1ed08424dd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-sex-14-container' and @title = 'Sex' and (text() = 'Sex' or . = 'Sex')]</value>
      <webElementGuid>86a885eb-8984-4e2e-b3c3-736735816dd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
