<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Wahid</name>
   <tag></tag>
   <elementGuidId>7bdde029-03f7-4558-a51a-6aa7efe3f7bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comments']/div/div[2]/ul/li[3]/div/div[2]/div/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>d410fbac-7e0d-4d3a-9524-bd65c06b58b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qodef-comment-name vcard</value>
      <webElementGuid>ed0b2f73-e95c-4aba-a173-c3be15c9ab40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
												Wahid					</value>
      <webElementGuid>c9e4315f-b21d-4dda-8e93-4e1bb2417cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comments&quot;)/div[@class=&quot;qodef-comment-holder-inner&quot;]/div[@class=&quot;qodef-comments&quot;]/ul[@class=&quot;qodef-comment-list&quot;]/li[3]/div[@class=&quot;qodef-comment clearfix&quot;]/div[@class=&quot;qodef-comment-text&quot;]/div[@class=&quot;qodef-comment-info&quot;]/h5[@class=&quot;qodef-comment-name vcard&quot;]</value>
      <webElementGuid>eded9b3d-360d-4004-bfe7-cb49fe6254a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comments']/div/div[2]/ul/li[3]/div/div[2]/div/h5</value>
      <webElementGuid>12beefb2-2685-4f36-9aeb-b8e79586e183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='reply'])[4]/following::h5[1]</value>
      <webElementGuid>ce2fae14-eea9-4038-a461-15e7864a34f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='February 22, 2018'])[3]/following::h5[1]</value>
      <webElementGuid>77f9f8dd-ae1d-42b4-9e0c-09caa82beae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September 14, 2023'])[1]/preceding::h5[1]</value>
      <webElementGuid>76d064d0-e24a-4628-a2a2-c09bd280671c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wahid']/parent::*</value>
      <webElementGuid>9c96c9eb-aa00-48b3-9e03-b4ac4501dd51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/div/h5</value>
      <webElementGuid>847a7e13-fb3b-43a0-9167-9cf00afc92b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '
												Wahid					' or . = '
												Wahid					')]</value>
      <webElementGuid>877c53ed-06c0-4c83-8913-31a5fb68fdd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
