<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cancel reply_submit</name>
   <tag></tag>
   <elementGuidId>6d7d6eba-c16a-4acd-b024-e2d469a64eac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit_comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submit_comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fbf75f6-a28f-4f7c-9bcb-c039850edc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>323dd1c1-0b2f-4d04-94c8-2b497f7cdb6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6561b89-e8b0-4897-999a-00af9d955852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_comment</value>
      <webElementGuid>99505cde-274d-4e9d-b708-c4aa26f27eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>70506950-ed48-4585-b93e-8031bee5b21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Post comment</value>
      <webElementGuid>e773665e-18ca-4c05-a87c-aacfe3ec9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_comment&quot;)</value>
      <webElementGuid>889ff08d-ebad-4d66-b3fa-85c41449dbfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='submit_comment']</value>
      <webElementGuid>282d64df-dc01-4229-8057-782be203ee1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/p/input</value>
      <webElementGuid>72beb880-8f02-4bfd-8be5-215afd2bfe51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/input</value>
      <webElementGuid>c57dae25-fd8d-4cac-9d6d-c820c9bdf789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'submit' and @type = 'submit' and @id = 'submit_comment']</value>
      <webElementGuid>d663419b-9670-4fa9-9bda-715ca2419120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
