<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cancel reply_author</name>
   <tag></tag>
   <elementGuidId>12c28d8b-e0d5-44d4-b02e-c3c02aa03da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#author</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='author']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5ceac1c-4b7f-4caa-8e1b-1c15caf9fa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>0fdc3136-86d1-4721-ae07-f691747efd7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>4aec9e3c-406f-458d-939c-4fa2a9880663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full name*</value>
      <webElementGuid>a667af04-62dd-4905-a85d-e96f013ed77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>37ea630a-c1dc-4995-8262-0a11da567dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e034e55-8613-4eca-a663-90524ab07ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author&quot;)</value>
      <webElementGuid>6c9f8e7c-0cde-4a8f-9f37-d460a92f9055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='author']</value>
      <webElementGuid>1ae7604a-688d-4e1b-a360-0a006648a3c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/input</value>
      <webElementGuid>9862b32d-deb7-4e8f-ba5e-0a053a08dcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>36289b58-80fb-4505-9f85-0ccff79aaeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'author' and @name = 'author' and @placeholder = 'Full name*' and @type = 'text']</value>
      <webElementGuid>e7be3597-7a0b-4a35-ac88-77e1277a7c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
