<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_First Comment</name>
   <tag></tag>
   <elementGuidId>7ff562e9-37be-4a77-8d71-a9faa15e5578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment-23 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='comment-23']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6f71b010-81a9-4d95-a92e-7a0057e42761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First Comment</value>
      <webElementGuid>6c34c4ee-0475-4eba-94ad-89000a772738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment-23&quot;)/p[1]</value>
      <webElementGuid>1d09d6fc-fdb4-4385-9529-8ba436b1bced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='comment-23']/p</value>
      <webElementGuid>71a4d74a-280c-404a-b00b-3e202e8fc40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='September 14, 2023'])[1]/following::p[1]</value>
      <webElementGuid>2e1637e7-912a-458b-bfda-8c53ecb27581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wahid'])[1]/following::p[1]</value>
      <webElementGuid>2f5184da-788c-4ef5-a486-a1a37698f053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel reply'])[1]/preceding::p[1]</value>
      <webElementGuid>c43eedc3-6e1b-4b62-857d-471efc7011bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='First Comment']/parent::*</value>
      <webElementGuid>a12cd2f8-8905-497a-b02e-64f573c16722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/div[2]/p</value>
      <webElementGuid>9666e7b6-5af9-43b2-9893-c56cc1bf57fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'First Comment' or . = 'First Comment')]</value>
      <webElementGuid>83fa21e5-ebef-4f1d-a6b1-38a45418e57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
