<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_cancel reply_comment</name>
   <tag></tag>
   <elementGuidId>8fd774f7-653d-4792-af67-20505b5b8cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>fd9255c3-69a2-41d9-bdc1-e36b9cc4a5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>22843b90-fade-4d06-aba4-ab66b7b7800c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>79cb73b1-28f4-4b54-86ab-4d440e19256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>1143bae0-e78a-46ce-bae4-ab6b8ad13280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>f75e6fb2-880d-407e-8cd6-3900f2f7912b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2b8e8271-28c1-4275-934e-53cd2a9c6c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d7c2a424-9602-4c20-a1c6-eac92c9fe9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;comment&quot;)</value>
      <webElementGuid>04a333d6-0d73-4b03-99cd-373a9161e361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='comment']</value>
      <webElementGuid>9c7036e7-d02c-4e3f-bfb7-5d4b2025d48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/textarea</value>
      <webElementGuid>f878590b-9fa9-42ca-bb33-fba9a47f6748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f81796b5-a85c-4be7-9292-c5105c6711fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'comment' and @placeholder = 'Comment' and @name = 'comment']</value>
      <webElementGuid>9d84653e-7ce4-4477-94d6-5584e71ede1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
