<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Schedule</name>
   <tag></tag>
   <elementGuidId>aebac978-ebc9-4166-8e5a-c363200fd3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-3848']/div/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qodef-post-title-area.qodef-no-thumbnail > div.qodef-post-title-area-inner > h5.qodef-post-title.entry-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>2dc180d5-3820-4ed3-81f1-b21cb5806e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>f10dff77-300a-4649-83c1-785499f5ac49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qodef-post-title entry-title</value>
      <webElementGuid>058abc39-f46b-4760-afc3-15969c6a61f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				        Schedule
			        </value>
      <webElementGuid>ebe2a36b-25b1-4c06-8548-a0ad3a90093e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-3848&quot;)/div[@class=&quot;qodef-post-content&quot;]/div[@class=&quot;qodef-post-title-area qodef-no-thumbnail&quot;]/div[@class=&quot;qodef-post-title-area-inner&quot;]/h5[@class=&quot;qodef-post-title entry-title&quot;]</value>
      <webElementGuid>23658b65-4032-4f2c-a11e-e8d6e71c29dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-3848']/div/div/div/h5</value>
      <webElementGuid>74d7c0ee-419f-4af1-b5f7-e56ca71286b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hot Yoga'])[1]/following::h5[1]</value>
      <webElementGuid>a70c68cb-2eb2-4c7b-88f4-840c2e9e3e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hatha Yoga'])[1]/following::h5[2]</value>
      <webElementGuid>90566309-e2c0-42f7-bef6-5a57fec17853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LESSMILLS BODYBALANCE'])[1]/preceding::h5[1]</value>
      <webElementGuid>6403261a-1a61-4005-8c06-8493ff29f42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[9]/div/div/div/h5</value>
      <webElementGuid>3a2ce541-744b-4d76-b69e-b6a1859dbf11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '
				        Schedule
			        ' or . = '
				        Schedule
			        ')]</value>
      <webElementGuid>fabaa3d1-dd21-40db-8d26-f9d2e80d8e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
