<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_News</name>
   <tag></tag>
   <elementGuidId>8d04987b-1eb3-4707-97e6-bd2087ae1ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-menu-item-3468 > a > span.item_outer > span.item_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='nav-menu-item-3468']/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f9c0926-4fb2-4436-a922-6c191acaee36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item_text</value>
      <webElementGuid>f89e7a82-672b-4661-b692-f20e9c4e44c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>News</value>
      <webElementGuid>6b0d52df-3bed-45f2-b19f-c6a07829c0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-menu-item-3468&quot;)/a[1]/span[@class=&quot;item_outer&quot;]/span[@class=&quot;item_text&quot;]</value>
      <webElementGuid>2c873b05-f09c-4cb5-ba72-e8929c8e90d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='nav-menu-item-3468']/a/span/span</value>
      <webElementGuid>ce6ae69b-f155-489c-ba84-83fbf9a7fab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/following::span[2]</value>
      <webElementGuid>2388b998-9bad-4f61-bf32-c4d6b858973f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule'])[1]/following::span[4]</value>
      <webElementGuid>c098bad9-b703-44aa-80bf-5f272b946a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::span[1]</value>
      <webElementGuid>67e54731-7d62-4c12-965f-3e6448ff9de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[2]/preceding::span[5]</value>
      <webElementGuid>b902d6a0-862f-49f4-ab76-2ed7878d4e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span/span</value>
      <webElementGuid>30c25933-1957-49d8-9a2a-076015a0c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'News' or . = 'News')]</value>
      <webElementGuid>3c8f7ee4-f104-4ae8-ae8f-c42cbfaa1c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
