<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Duplicate comment detected it looks as th_85686f</name>
   <tag></tag>
   <elementGuidId>d63e55e4-d589-4ee2-840b-03b2ed4e3b99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='error-page']/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1615ae3e-345b-470f-8448-0bed819de5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Duplicate comment detected; it looks as though you’ve already said that!</value>
      <webElementGuid>9ced7484-733a-4382-9282-dce9c936aa9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;error-page&quot;)/p[2]</value>
      <webElementGuid>a5814afc-1a50-42bc-b28d-623252db48df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='error-page']/p[2]</value>
      <webElementGuid>a525da63-5718-4635-8ad1-a64a2537bace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='« Back'])[1]/preceding::p[2]</value>
      <webElementGuid>e73492f5-d0d4-46f7-91b8-2585507fd5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'error-page', '&quot;', ')/p[2]')])[1]/preceding::p[3]</value>
      <webElementGuid>0aa20dfe-75d7-4ab8-8009-c7ecb685fdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Duplicate comment detected; it looks as though you’ve already said that!']/parent::*</value>
      <webElementGuid>3e5a48a5-c637-4a8e-9f75-ceafa1362f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>848f21b3-1caf-4c06-aa79-dcfd6b50e6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Duplicate comment detected; it looks as though you’ve already said that!' or . = 'Duplicate comment detected; it looks as though you’ve already said that!')]</value>
      <webElementGuid>f6d1061e-61f0-466c-9732-ff266172e1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
