<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cancel reply_author</name>
   <tag></tag>
   <elementGuidId>9a506100-ccb8-4615-a736-8c0941bb5115</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#author</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='author']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae755e50-7633-4b10-a2b9-4701b9cb6c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>e02dd904-58b3-45ab-97f7-f975ce3836fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>author</value>
      <webElementGuid>c7772ea4-002b-4253-9592-a83cb83807d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full name*</value>
      <webElementGuid>e0f2d0a1-c90f-454f-9f81-37df9e77335b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>262eee7e-5206-4c6d-9e64-49bdb6e2bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b19afb13-3792-4f25-8288-a1df2e4b63a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;author&quot;)</value>
      <webElementGuid>b28ff91c-91c7-4c55-afc6-51c82c1dd314</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='author']</value>
      <webElementGuid>4744d1a8-dc62-4ffa-b1eb-9dc4e18929ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='commentform']/input</value>
      <webElementGuid>8cd8109d-7cf4-4796-b51b-d38d1ad0af8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/input</value>
      <webElementGuid>a785330d-5513-4a39-8442-d7bb72530e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'author' and @name = 'author' and @placeholder = 'Full name*' and @type = 'text']</value>
      <webElementGuid>8ce209f1-b7bb-4294-87ec-791a1151f681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
