<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select quantity12345</name>
   <tag></tag>
   <elementGuidId>d71f722a-63ba-4079-96ed-8ca1ec656fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='quantity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f500bfb4-adee-4c8d-81ce-6339c12255ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>de794973-3922-4b36-b231-bfd1b7f00243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>d1da9ff1-9007-4d17-a2f3-0084436bca48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>2b57d50d-8691-4998-bd8e-f05a34570aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select quantity1&quot;2&quot;3&quot;4&quot;5&quot;</value>
      <webElementGuid>4b7a02e8-9748-4ad6-8d72-ecadcd63d898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity&quot;)</value>
      <webElementGuid>f3660e27-4e41-4d56-ba51-c27b6ceae287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='quantity']</value>
      <webElementGuid>1cc55f2a-c3d9-42ca-9827-e5210090f386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[4]/div/select</value>
      <webElementGuid>649f617d-43ae-4fba-b4e3-4fc6443737cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::select[1]</value>
      <webElementGuid>d0568641-eb08-479c-a30f-616ce41e2261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/following::select[2]</value>
      <webElementGuid>d886052d-3d54-4e9a-9a13-8352574bb565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::select[1]</value>
      <webElementGuid>56b0d251-3b31-412f-a3ba-b84ba8bbb17c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&quot;']/parent::*</value>
      <webElementGuid>6f8ec43b-fc84-4a0e-9586-65d81c99a44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>b1c97369-db05-46b7-8686-600a94ec7f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'quantity' and @id = 'quantity' and (text() = 'Select quantity1&quot;2&quot;3&quot;4&quot;5&quot;' or . = 'Select quantity1&quot;2&quot;3&quot;4&quot;5&quot;')]</value>
      <webElementGuid>3e334ce4-42c4-4f6c-a177-bb6dcf2e6a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
