<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select time1930 - 20301930 - 2030193_dcfdca</name>
   <tag></tag>
   <elementGuidId>d6afc20a-f2ff-48d2-aa9c-27950b9eac34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#time_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='time_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae778031-e2ee-4fe1-a496-50a3655d4039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>1a5d4f09-b1e8-4796-aa82-2dec76b37303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time_id</value>
      <webElementGuid>7f538dc0-e4ae-4450-bba8-4b4afb59e177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>time_id</value>
      <webElementGuid>d9e1fcfb-69da-4aaa-9c29-24d8fd9a23ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select time19:30 - 20:3019:30 - 20:3019:30 - 20:30</value>
      <webElementGuid>c0972c8b-31d2-4bc2-b83b-d84c684190d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;time_id&quot;)</value>
      <webElementGuid>4d1ed1df-3cb3-481e-af6e-997f1ffb70b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='time_id']</value>
      <webElementGuid>338369c4-bca2-4562-adb0-e16218e6c44e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[3]/div/select</value>
      <webElementGuid>c99273d0-325e-4f22-aa33-af6493441a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/following::select[1]</value>
      <webElementGuid>43ac72d5-ab9e-4bf3-b477-c2ec972ab29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/following::select[2]</value>
      <webElementGuid>688e313b-a1a1-4c6c-8c46-dc6b5cd329f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::select[1]</value>
      <webElementGuid>8b15a5d4-1540-4fb8-971e-fb05f3a8f7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::select[2]</value>
      <webElementGuid>5aac8037-6c1a-40f4-9b74-033d777f2dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>339e4076-0b7d-4bbb-9f2b-784430dc1c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'time_id' and @id = 'time_id' and (text() = 'Select time19:30 - 20:3019:30 - 20:3019:30 - 20:30' or . = 'Select time19:30 - 20:3019:30 - 20:3019:30 - 20:30')]</value>
      <webElementGuid>0ae63c7f-7c3b-4ef0-a38b-8df83b0b02ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
