<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select dateTuesday, 26 August 2025</name>
   <tag></tag>
   <elementGuidId>033b1d92-0362-4ecf-96ca-f6922b778cbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#date_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a545733-4338-4369-b1b0-a1ea68393789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>bec6ca05-5945-43d4-b2ba-3d63e1acf752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>b9cef3e1-4f15-4d8a-b3d9-89711ec8e70a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>12c13546-69dd-4dce-8fe1-c7a729b86d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select dateTuesday, 26 August 2025</value>
      <webElementGuid>d577142c-e762-4efc-a2c2-981762767fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_id&quot;)</value>
      <webElementGuid>d65653de-bac4-447f-9d8c-c87f6dc7d5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_id']</value>
      <webElementGuid>6af9b663-90c5-42cb-9bd6-2d05e1a74a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[2]/div/select</value>
      <webElementGuid>755a73fb-8755-4c06-8d3e-377585ce7471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/following::select[1]</value>
      <webElementGuid>8aa5339e-0536-4821-b4ee-1e3b8a615a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a class'])[1]/following::select[2]</value>
      <webElementGuid>13451a36-6e04-4667-ab83-afb6e093c5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/preceding::select[1]</value>
      <webElementGuid>c7541ba4-fbec-4772-bc71-8c3e21027830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::select[2]</value>
      <webElementGuid>bda703a3-0a55-4197-846a-5a8a6aa18257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>feac8d71-7830-4ebb-8b70-a35038a703a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'date_id' and @id = 'date_id' and (text() = 'Select dateTuesday, 26 August 2025' or . = 'Select dateTuesday, 26 August 2025')]</value>
      <webElementGuid>fe8d8411-a86c-41ef-9b96-c0f9fe94fb4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
