<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select dateWednesday, 26 August 2026</name>
   <tag></tag>
   <elementGuidId>fec4aa72-d16e-4ba7-a69d-b599cdeb4703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#date_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='date_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e86544a9-4dc6-4a3d-9170-e54686cbd9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-border</value>
      <webElementGuid>e194ca79-fb28-4761-8bd9-611d12a7075c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>aff8f084-a913-4f83-a40b-abe4529575e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>date_id</value>
      <webElementGuid>02fdc280-c01e-4a78-ad58-7431a39ffd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select dateWednesday, 26 August 2026</value>
      <webElementGuid>0f5eec4b-b19a-4493-9072-5f926710db49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;date_id&quot;)</value>
      <webElementGuid>346c9840-4f96-4837-ade4-8b74f857ff19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='date_id']</value>
      <webElementGuid>2cbd584d-107b-4a5b-8975-ae601fd47f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-landing']/form/div[2]/div/select</value>
      <webElementGuid>ea6c8a2d-73e6-4fbc-80c3-83fc3b0137c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/following::select[1]</value>
      <webElementGuid>eaf8ee0e-9922-4f9e-93d0-81d564c83e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a class'])[1]/following::select[2]</value>
      <webElementGuid>87a11ccb-21b0-45d6-bbd6-370ce833cf96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available hour'])[1]/preceding::select[1]</value>
      <webElementGuid>951d4f7b-9a64-4776-acb3-1ea2ffb51efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::select[2]</value>
      <webElementGuid>a8beae4b-60c8-48dc-8fa1-02aa5bd6c583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>62350532-8d88-478f-9925-b53ae3b770c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'date_id' and @id = 'date_id' and (text() = 'Select dateWednesday, 26 August 2026' or . = 'Select dateWednesday, 26 August 2026')]</value>
      <webElementGuid>6dbdc13a-c7d7-477a-bc48-1505f505d900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
