<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Contact Us_qodef-icon-ion-icon ion-androi_846845</name>
   <tag></tag>
   <elementGuidId>320d046e-4641-4926-a1c5-7d2475749eeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e5f1c020-434d-4d2e-b443-f5481926f7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qodef-icon-ion-icon ion-android-search </value>
      <webElementGuid>7b02685b-293a-4cf9-a9b1-d6c033aae4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext no-touch hashchange history draganddrop rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio svg inlinesvg svgclippaths&quot;]/body[@class=&quot;search search-results paged paged-2 search-paged-2 qodef-bmi-calculator-1.2 prowess-core-1.0.1 prowess-ver-1.2 qodef-grid-1300 qodef-light-header qodef-sticky-header-on-scroll-up qodef-dropdown-animate-height qodef-header-standard qodef-menu-area-shadow-disable qodef-menu-area-in-grid-shadow-disable qodef-menu-area-border-disable qodef-menu-area-in-grid-border-disable qodef-logo-area-border-disable qodef-header-vertical-shadow-disable qodef-header-vertical-border-disable qodef-side-menu-slide-from-right qodef-default-mobile-header qodef-sticky-up-mobile-header wpb-js-composer js-comp-ver-5.5.2 vc_responsive qodef-fullscreen-search qodef-search-fade&quot;]/div[@class=&quot;qodef-wrapper&quot;]/div[@class=&quot;qodef-wrapper-inner&quot;]/header[@class=&quot;qodef-page-header&quot;]/div[@class=&quot;qodef-menu-area qodef-menu-right&quot;]/div[@class=&quot;qodef-grid&quot;]/div[@class=&quot;qodef-vertical-align-containers&quot;]/div[@class=&quot;qodef-position-right&quot;]/div[@class=&quot;qodef-position-right-inner&quot;]/a[@class=&quot;qodef-search-opener qodef-icon-has-hover qodef-search-opener-icon-pack&quot;]/span[@class=&quot;qodef-search-opener-wrapper&quot;]/i[@class=&quot;qodef-icon-ion-icon ion-android-search&quot;]</value>
      <webElementGuid>a9fea0bf-92ee-4500-8537-d2e48e6159fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>b07eef09-72db-4556-8d7d-07176dacebc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
