<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Fitness</name>
   <tag></tag>
   <elementGuidId>7a1e1e45-cc23-4ac4-893a-9187a3d63104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-2890']/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.qodef-post-info-category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d7c06177-be17-45ae-bab8-51735dd1512f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qodef-post-info-category</value>
      <webElementGuid>0bdadee1-c66d-4d04-95ef-ebe75e6eddc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Fitness</value>
      <webElementGuid>dd531eea-6296-4c86-a4a3-6382e633ded7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-2890&quot;)/div[@class=&quot;qodef-post-info-bottom clearfix&quot;]/div[@class=&quot;qodef-post-info-bottom-left&quot;]/div[@class=&quot;qodef-post-info-category&quot;]</value>
      <webElementGuid>f577be7f-402d-4e04-9281-5d7473df7d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-2890']/div[3]/div/div</value>
      <webElementGuid>da05ceb0-2197-4c96-9c85-26018ac42c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eating Habit For Best Performance'])[1]/following::div[6]</value>
      <webElementGuid>2abc1cbe-aca6-48fd-a442-575b88fc8832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Performance'])[1]/following::div[30]</value>
      <webElementGuid>c04a8d53-ae4e-40c8-b2f9-8aef768d7289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='previous'])[1]/preceding::div[2]</value>
      <webElementGuid>e86e3951-aff8-49c2-9da7-8ef1902b99a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div[3]/div/div</value>
      <webElementGuid>03b06c35-b8a6-470c-9d45-79763ce37a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    Fitness' or . = '
    Fitness')]</value>
      <webElementGuid>4dd9c32f-d133-4b2c-b769-0ea4e11fa4ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
