<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_infofitbybeat.com_wpcf7-form-control _242eeb</name>
   <tag></tag>
   <elementGuidId>05678001-c571-44a9-9c94-8e43c0625044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Send']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.wpcf7-form-control.wpcf7-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d97b71ec-fcfc-4db0-aa44-1d4899171bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c4fd9894-f827-4709-a96c-eab60d40c404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Send</value>
      <webElementGuid>9a0c2a81-2af2-497b-9f55-8050c5e9dfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-submit</value>
      <webElementGuid>9aaeffed-5062-44fa-8be5-97f14888c9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1104-p1774-o1&quot;)/form[@class=&quot;wpcf7-form&quot;]/div[2]/div[@class=&quot;qodef-grid-row&quot;]/div[@class=&quot;qodef-grid-col-12&quot;]/div[@class=&quot;qodef-btn qodef-btn-small qodef-btn-solid qodef-btn-icon qodef-custom-cf-7-button&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-submit&quot;]</value>
      <webElementGuid>629973f5-86a7-48e1-af71-55f0fcd8e564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Send']</value>
      <webElementGuid>468ba2f3-ca4a-4a69-81a4-13596c9f3c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1104-p1774-o1']/form/div[2]/div[4]/div/div/input</value>
      <webElementGuid>d1ff1d5f-f30b-4d0a-9730-1bc8565711b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>507d8b54-7612-4156-8c6b-0d9dd01224e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>7b2d0241-5c5d-4b58-82f3-803685c8e0e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
