<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_infofitbybeat.com_last-name</name>
   <tag></tag>
   <elementGuidId>74924a47-bea8-4735-9a33-a3960e13e221</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='last-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;last-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f661227-958a-41f6-a1d0-fccf780048fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b97c89e4-2f15-4a7d-8bd3-66eba497bd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>last-name</value>
      <webElementGuid>f84a4d2a-52d5-4b49-99a6-007e7ba90e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>65eac170-9636-466c-8006-501f078f278a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text wpcf7-validates-as-required</value>
      <webElementGuid>572c5723-c615-4ba5-b439-63759a9ed5cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>39bd08e6-c564-4b81-a02b-3948ff1ece0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e4c97472-008e-4f57-ba74-f46039ded47b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>debafeaf-eb6c-4ee0-af0b-3f19fc53318e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1104-p1774-o1&quot;)/form[@class=&quot;wpcf7-form&quot;]/div[2]/div[@class=&quot;qodef-grid-row mkd-grid-tiny-gutter&quot;]/div[@class=&quot;qodef-grid-col-12&quot;]/span[@class=&quot;wpcf7-form-control-wrap last-name&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>d36e7385-85bc-42fa-95c9-66588274cb30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='last-name']</value>
      <webElementGuid>984a069d-5109-41aa-b071-548b91e3024d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1104-p1774-o1']/form/div[2]/div/div[2]/span/input</value>
      <webElementGuid>dfbedd47-9c62-41bd-9352-e1119ebd1165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/input</value>
      <webElementGuid>d82ac2cc-895b-43ed-a364-d27aa389f1c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'last-name' and @placeholder = 'Last Name']</value>
      <webElementGuid>84525dbe-0e3c-4575-bfa2-a43761ee2fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
