<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_infofitbybeat.com_email</name>
   <tag></tag>
   <elementGuidId>ae4b605e-e705-4054-a2f1-f4e87bbaf236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f382f20-e1b7-443f-ba75-0046744c7db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82e6f317-ad7f-4540-a4d3-dca0bd318b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>24415301-ba70-4c85-977b-cac4b59ed375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>6a30f4f3-d279-450e-852b-a9e9b8aedd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpcf7-form-control wpcf7-text wpcf7-validates-as-required</value>
      <webElementGuid>0cb1fd6c-1f0c-4ff7-bd7a-849934819019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5cae98b4-b7db-4031-8849-12b6881d78d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>48172757-cc94-4561-9611-366e107b8c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>62d1cb10-c9e6-45d4-92a5-d0647551dc37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpcf7-f1104-p1774-o1&quot;)/form[@class=&quot;wpcf7-form&quot;]/div[2]/div[@class=&quot;qodef-grid-row mkd-grid-tiny-gutter&quot;]/div[@class=&quot;qodef-grid-col-12&quot;]/span[@class=&quot;wpcf7-form-control-wrap email&quot;]/input[@class=&quot;wpcf7-form-control wpcf7-text wpcf7-validates-as-required&quot;]</value>
      <webElementGuid>7b2c312e-3ece-48cd-9a76-5f64d08a1ff2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>450e8d21-5ec2-49e5-b2e9-251c784adf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpcf7-f1104-p1774-o1']/form/div[2]/div[2]/div[2]/span/input</value>
      <webElementGuid>d50742e3-d8df-4dd2-9cd2-e5b26f9faa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>2bafa153-e89e-4e50-969a-6649b232b9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>cbb4a48a-657f-4e2a-9057-cbb52afb616c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
